### ISSUE TITLE
HADR disabled

### ISSUE THREAD

**Issue by 06212** [imperva/dsfkit#381]
Hello Imperva,

I would have suggestion for improving the code in your repo. 

We only would like to deploy DSF, DRA Admin, DRA Analytics in one region (without HADR instances deployed in second region) with below configuration

enable_dam = false
agentless_gw_count = 0
agent_gw_count = 0
hub_hadr = false
agentless_gw_hadr = false
dra_version = "4.14"
aws_profile  = ""
aws_region_1 = "us-east-1"
aws_region_2 = ""

│ Error: Invalid AWS Region:  
│   with provider["registry.terraform.io/hashicorp/aws"].provider-2,
│   on providers.tf line 13, in provider "aws":
│   13: provider "aws" {

The terraform is still expecting second region.  We found a the solution as changing the logic for hub_dr_public_ip & hub_dr_ip from below file:

[https://github.com/imperva/dsfkit/blob/master/examples/aws/installation/dsf_single_account_deployment/sonar.tf](url)
```
hub_dr_public_ip = var.enable_sonar && var.hub_hadr ? (length(module.hub_dr[0].public_ip) > 0 ? format("%s/32", module.hub_dr[0].public_ip) : null) : null
hub_dr_ip = var.enable_sonar && var.hub_hadr ? (length(module.hub_dr[0].public_dns) > 0 ? module.hub_dr[0].public_dns : module.hub_dr[0].private_dns) : null
```

Could you please review and the code change and and add it as fix, or advise if there is another way of deploying the resources without HADR?

Thank you!

**Comment by lindanasredin** [comment]
Hello 06212,

Thank you for approaching Imperva.

The example dsf_single_account_deplopyment that you are using supports deployments with disabled HADR.
The reason you are getting the error is because an empty string is an invalid AWS region: aws_region_2 = ""
This is also an invalid configuration: aws_profile = ""

In this example's README it says:

'''
This deployment consists of:

1. Main and DR DSF Hub in region 1
2. Main and DR Agentless Gateway Hub in region 2
3. DAM MX in region 1
4. DAM Agent Gateway in region 2
5. DRA Admin in region 1
6. DRA Analytics in region 2
7. DSF Hub HADR setup
8. Agentless Gateway HADR setup
9. Federation of both main and DR DSF Hub with all main and DR Agentless Gateways
10. Integration from MX to DSF Hub (Audit from Agent source and Security Issues)
'''

You mentioned that you want to deploy DSF Hub, DRA Admin and DRA Analytics.
These are the items in the list:

1. Main and DR DSF Hub in region 1
2. 5. DRA Admin in region 1
6. DRA Analytics in region 2
(also 9)

This means that you need to provide 2 regions.
They can be the same one if you want, like this:
aws_region_1 = "us-east-1"
aws_region_2 = "us-east-1"

In addition, in this example's README it says:

'''
It is mandatory to provide as input to this example the following variables:

1. The AWS profile of the DSF nodes' AWS account
2. The AWS regions of the DSF nodes
3. The subnets in which to deploy the DSF nodes, they can be in the same or in different subnets
'''
So in addition to providing the AWS profile and regions, for example:

aws_profile = "myProfile"
aws_region_1 = "us-east-1"
aws_region_2 = "us-east-2"

You need to provide the subnets:

subnet_ids = {
  hub_main_subnet_id               = "subnet-xxxxxxxxxxxxxxxx1"
  hub_dr_subnet_id                 = "subnet-xxxxxxxxxxxxxxxx2"
  agentless_gw_main_subnet_id      = "subnet-xxxxxxxxxxxxxxxx3"
  agentless_gw_dr_subnet_id        = "subnet-xxxxxxxxxxxxxxxx4"
  mx_subnet_id                     = "subnet-xxxxxxxxxxxxxxxx5"
  agent_gw_subnet_id               = "subnet-xxxxxxxxxxxxxxxx6"
  dra_admin_subnet_id              = "subnet-xxxxxxxxxxxxxxxx7"
  dra_analytics_subnet_id          = "subnet-xxxxxxxxxxxxxxxx8"
}

Currently we have a limitation that you have to provide all the subnets even if you are not deploying DAM and Agentless Gateway. So please just copy and paste the DSF Hub's subnet, for example, to the irrelevant subnets. Thanks.

**Comment by 06212** [comment]
Hey Linda,Thank for detail response.I will redeploy the infrastructure with your suggestion right now.Thanks,IliyaSent from my iPhoneOn 13 Feb 2024, at 11:55, Linda Nasredin ***@***.***> wrote:﻿
Hello 06212,
Thank you for approaching Imperva.
The example dsf_single_account_deplopyment that you are using supports deployments with disabled HADR.
The reason you are getting the error is because an empty string is an invalid AWS region: aws_region_2 = ""
This is also an invalid configuration: aws_profile = ""
In this example's README it says:
'''
This deployment consists of:

Main and DR DSF Hub in region 1
Main and DR Agentless Gateway Hub in region 2
DAM MX in region 1
DAM Agent Gateway in region 2
DRA Admin in region 1
DRA Analytics in region 2
DSF Hub HADR setup
Agentless Gateway HADR setup
Federation of both main and DR DSF Hub with all main and DR Agentless Gateways
Integration from MX to DSF Hub (Audit from Agent source and Security Issues)
'''

You mentioned that you want to deploy DSF Hub, DRA Admin and DRA Analytics.
These are the items in the list:

Main and DR DSF Hub in region 1


DRA Admin in region 1


DRA Analytics in region 2
(also 9)

This means that you need to provide 2 regions.
They can be the same one if you want, like this:
aws_region_1 = "us-east-1"
aws_region_2 = "us-east-1"
In addition, in this example's README it says:
'''
It is mandatory to provide as input to this example the following variables:

The AWS profile of the DSF nodes' AWS account
The AWS regions of the DSF nodes
The subnets in which to deploy the DSF nodes, they can be in the same or in different subnets
'''
So in addition to providing the AWS profile and regions, for example:

aws_profile = "myProfile"
aws_region_1 = "us-east-1"
aws_region_2 = "us-east-2"
You need to provide the subnets:
subnet_ids = {
hub_main_subnet_id               = "subnet-xxxxxxxxxxxxxxxx1"
hub_dr_subnet_id                 = "subnet-xxxxxxxxxxxxxxxx2"
agentless_gw_main_subnet_id      = "subnet-xxxxxxxxxxxxxxxx3"
agentless_gw_dr_subnet_id        = "subnet-xxxxxxxxxxxxxxxx4"
mx_subnet_id                     = "subnet-xxxxxxxxxxxxxxxx5"
agent_gw_subnet_id               = "subnet-xxxxxxxxxxxxxxxx6"
dra_admin_subnet_id              = "subnet-xxxxxxxxxxxxxxxx7"
dra_analytics_subnet_id          = "subnet-xxxxxxxxxxxxxxxx8"
}
Currently we have a limitation that you have to provide all the subnets even if you are not deploying DAM and Agentless Gateway. So please just copy and paste the DSF Hub's subnet, for example, to the irrelevant subnets. Thanks.

**Comment by lindanasredin** [comment]
Good luck Iliya!
